title: Immutant

profiles:
  staging:
    base_url: http://staging.immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/staging/htdocs
  production:
    base_url: http://immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/www/htdocs
  development:
    disqus_developer: true

disqus: immutant
google_analytics: UA-6435340-7

latest_plugin_version: 1.0.0.beta3
