title: Immutant

profiles:
  staging:
    base_url: http://staging.immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/staging/htdocs
  production:
    base_url: http://immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/www/htdocs
intense_debate_acct: 350476a030c25a50bd9e5b33c5c937f3
google_analytics: UA-6435340-7

