title: Immutant

profiles:
  staging:
    base_url: http://staging.immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/staging/htdocs
  production:
    base_url: http://immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/www/htdocs

intense_debate_base_url: http://immutant.org
intense_debate_acct: 82f59e335081be13846c34fa627b3208
google_analytics: UA-6435340-7

