title: Immutant

profiles:
  staging:
    base_url: http://staging.immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/staging/htdocs
  production:
    base_url: http://immutant.org/
    deploy:
      host: immutant.org
      path: /var/www/domains/immutant.org/www/htdocs
  development:
    disqus_developer: true

disqus: immutant
google_analytics: UA-6435340-7

quick_links:
  - [ Latest Build, http://immutant.org/builds/immutant-dist-bin.zip ]
  - [ Latest Docs, http://immutant.org/builds/LATEST/html-docs/index.html ]
  - [ Issues, https://issues.jboss.org/browse/IMMUTANT ]
  - [ Chat, 'http://webchat.freenode.net/?channels=immutant', '#immutant on freenode' ]
  - [ Source, https://github.com/immutant/immutant ]
